### ISSUE TITLE
class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by effeaucarre** [dialectlabs/actions#3]
Hello,

i cloned the repo, npm install, but when i npm run dev, i get the following error : 

actions\node_modules\@hono\node-server\dist\index.js:59
```
var Request = class extends GlobalRequest {
              ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (C:\Users\frede\www\artrade\actions\node_modules\@hono\node-server\dist\index.js:59:15)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.transformer (C:\Users\frede\www\artrade\actions\node_modules\tsx\dist\register-DfubRCxM.cjs:2:823)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at jupiterSwap (c:\Users\frede\www\artrade\actions\examples\index.ts:1:23)
    at Object.<anonymous> (c:\Users\frede\www\artrade\actions\examples\index.ts:42:2)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
```

any idea how to fix this ?

thanks !

**Comment by sean01859** [comment]
Try it with node v18.

**Comment by trentbrooks** [comment]
I have the same error using node v18.9

**Comment by effeaucarre** [comment]
> Try it with node v18.

apparently it works on my side with node v18.14

**Comment by effeaucarre** [comment]
> I have the same error using node v18.9

try node v18.14 at least, apparently hono requires this version as a minimum
